classdef kConcatenate3Layer115949 < nnet.layer.Layer & nnet.layer.Formattable & ...
        nnet.layer.AutogeneratedFromTensorFlow & nnet.layer.Acceleratable
    %kConcatenate3Layer115949
    % Auto-generated by MATLAB on 24-Feb-2025 20:38:32
    
    
    properties
        % Non Trainable Parameters
        
    end
    
    properties (Learnable)
        % Trainable parameters
        
    end
    
    properties (Hidden)
        % Code literals
        
        InputLabels
        OutputLabels
        IsTraining
    end
    
    methods
        function obj = kConcatenate3Layer115949(Name, Type)
            obj.Name = Name;
            obj.Type = Type;
            obj.IsTraining = false;
            obj.NumInputs = 2;
            obj.NumOutputs = 1;
            obj.InputLabels = {'',''};
            obj.OutputLabels = {'fcs'};
        end
        
        function varargout = predict(obj, inputs0, inputs1)
            import LSTM_car.ops.*;
            obj.InputLabels{1} = inputs0.dims;
            
            inputs0 = iPermuteToReverseTF(inputs0, 3);
            
            obj.InputLabels{2} = inputs1.dims;
            
            inputs1 = iPermuteToReverseTF(inputs1, 3);
            temp{1} = Concatenate3Layer115949(inputs0, inputs1, obj);
            
            % Extract results from function call.
            temp{1} = addOutputLabel(temp{1}, 1, obj);
            varargout{1} = iPermuteToForwardTF(temp{1}.value, temp{1}.rank);
        end
        
        function varargout = forward(obj, inputs0, inputs1)
            obj.IsTraining = true;
            import LSTM_car.ops.*;
            obj.InputLabels{1} = inputs0.dims;
            
            inputs0 = iPermuteToReverseTF(inputs0, 3);
            
            obj.InputLabels{2} = inputs1.dims;
            
            inputs1 = iPermuteToReverseTF(inputs1, 3);
            temp{1} = Concatenate3Layer115949(inputs0, inputs1, obj);
            
            % Extract results from function call.
            temp{1} = addOutputLabel(temp{1}, 1, obj);
            varargout{1} = iPermuteToForwardTF(temp{1}.value, temp{1}.rank);
        end
    end
end

function [identity] = Concatenate3Layer115949(inputs0, inputs1, obj)
import LSTM_car.ops.*;

inputs0 = struct('value', inputs0, 'rank', 3);
inputs1 = struct('value', inputs1, 'rank', 3);

concatAxis = struct('value', double(1), 'rank', 0);
concat = tfCat(concatAxis, inputs0, inputs1);
Identity = struct('value', concat.value, 'rank', 3);

% assigning outputs
identity = Identity;
end

